### ISSUE TITLE
Failed to use cuda 

### ISSUE THREAD

**Issue by M9JS** [CederGroupHub/chgnet#38]
I tried running on GPU for faster structure optimization by setting `use_device="cuda"` in `MolecularDynamics`.

```py
from chgnet.model.model import CHGNet
from chgnet.model.dynamics import MolecularDynamics
from pymatgen.core import Structure

structure = Structure.from_file("examples/o-LiMnO2_unit.cif")
chgnet = CHGNet.load()

md = MolecularDynamics(
    atoms=structure,
    model=chgnet,
    ensemble="nvt",
    compressibility_au=1.6,
    temperature=1000,  # in K
    timestep=2,  # in femto-seconds
    trajectory="md_out.traj",
    logfile="md_out.log",
    loginterval=100,
    use_device="cuda",  # use 'cuda' for faster MD
)
md.run(50)  # run a 0.1 ps MD simulation
```

But in the head of out put, it showed

```txt
CHGNet initialized with 400438 Parameters
CHGNet will run on cpu
```

Did I miss any step? Additionally, I wonder if cuda is avaliable in structure optimization.

**Comment by janosh** [comment]
I can't repro this. Perhaps the line

```txt
CHGNet will run on cpu
```

comes from some other call to CHGnet not shown in your pasted code snippet? You can post the complete script and complete run logs?

**Comment by janosh** [comment]
Also, if you want to optimize a structure, don't use `MolecularDynamics`. There's a dedicated

https://github.com/CederGroupHub/chgnet/blob/73d3219fc77b581a57de86550bdb9e5ebdc8068f/chgnet/model/dynamics.py#L126

**Comment by M9JS** [comment]
Thanks for the reply. I know I should use StructOptimizer for structure optimization. I tried to set `use_device="cuda"` in both MD and Structure Optimization cases but neither of them worked.
Here is the code for structure optimization.
```
from chgnet.model.model import CHGNet
from pymatgen.core import Structure
from chgnet.model import StructOptimizer
import sys

#polymorphs = ['alpha-V2O5', 'beta-V2O5', 'theta-V2O5', 'gamma-V2O5', 'R-V2O5', 'zeta-V2O5']
polymorphs = ['Ta-V2O5', 'alpha-V2O5']

log_file = open("output.log", "w")
sys.stdout = log_file

for item in polymorphs:
    filepath = 'cif/' + item + '.cif'
    chgnet = CHGNet.load()
    structure = Structure.from_file(filepath)
    relaxer = StructOptimizer(use_device="cuda")
    result = relaxer.relax(structure)
    print(item + " relaxation done")
    print("CHGNet relaxed structure", result["final_structure"])

log_file.close()
```

And here is the run log of it

```
CHGNet initialized with 400438 Parameters
CHGNet initialized with 400438 Parameters
CHGNet will run on cpu
      Step     Time          Energy         fmax
*Force-consistent energies used in optimization.
FIRE:    0 10:06:19     -113.530169*      37.8197
FIRE:    1 10:06:26     -110.316457*      83.7187
FIRE:    2 10:06:31     -113.499166*      44.0090
FIRE:    3 10:06:37     -114.744669*      29.4197
FIRE:    4 10:06:43     -115.582325*       0.8105
FIRE:    5 10:06:49     -114.859652*      30.3049
FIRE:    6 10:06:55     -115.026278*      26.3967
FIRE:    7 10:07:01     -115.277805*      19.0960
FIRE:    8 10:07:04     -115.493805*      10.0925
FIRE:    9 10:07:11     -115.593687*       1.8824
FIRE:   10 10:07:17     -115.560308*       5.8469
FIRE:   11 10:07:23     -115.562218*       5.7091
FIRE:   12 10:07:28     -115.565889*       5.4376
FIRE:   13 10:07:34     -115.570963*       5.0399
FIRE:   14 10:07:39     -115.577011*       4.5269
FIRE:   15 10:07:45     -115.583500*       3.9126
FIRE:   16 10:07:51     -115.589828*       3.2130
FIRE:   17 10:07:56     -115.595530*       2.4459
FIRE:   18 10:08:02     -115.600510*       1.5445
FIRE:   19 10:08:08     -115.603968*       0.5767
FIRE:   20 10:08:09     -115.605209*       0.5589
FIRE:   21 10:08:15     -115.605276*       0.5590
FIRE:   22 10:08:21     -115.605356*       0.5592
FIRE:   23 10:08:27     -115.605463*       0.5595
FIRE:   24 10:08:33     -115.605637*       0.5598
FIRE:   25 10:08:38     -115.605837*       0.5603
FIRE:   26 10:08:44     -115.606077*       0.5608
FIRE:   27 10:08:50     -115.606358*       0.5614
FIRE:   28 10:08:56     -115.606678*       0.5621
FIRE:   29 10:09:02     -115.607119*       0.5630
FIRE:   30 10:09:07     -115.607626*       0.5639
FIRE:   31 10:09:13     -115.608240*       0.5650
FIRE:   32 10:09:19     -115.609001*       0.5661
FIRE:   33 10:09:25     -115.609896*       0.5672
FIRE:   34 10:09:31     -115.610977*       0.5681
FIRE:   35 10:09:33     -115.612286*       0.5687
FIRE:   36 10:09:39     -115.613888*       0.5686
FIRE:   37 10:09:45     -115.615837*       0.5676
FIRE:   38 10:09:51     -115.618200*       0.5652
FIRE:   39 10:09:57     -115.621084*       0.5612
FIRE:   40 10:10:02     -115.624529*       0.5553
FIRE:   41 10:10:08     -115.628628*       0.5477
FIRE:   42 10:10:14     -115.633394*       0.5388
FIRE:   43 10:10:19     -115.639015*       0.5295
FIRE:   44 10:10:26     -115.645651*       0.5206
FIRE:   45 10:10:31     -115.653355*       0.5123
FIRE:   46 10:10:38     -115.662167*       0.5028
FIRE:   47 10:10:43     -115.672207*       0.4888
FIRE:   48 10:10:48     -115.683609*       0.4680
FIRE:   49 10:10:54     -115.696333*       0.4429
FIRE:   50 10:11:01     -115.710579*       0.4202
FIRE:   51 10:11:06     -115.726467*       0.3997
FIRE:   52 10:11:07     -115.744225*       0.3695
FIRE:   53 10:11:12     -115.763971*       0.3326
FIRE:   54 10:11:19     -115.785721*       0.3092
FIRE:   55 10:11:25     -115.809139*       0.2686
FIRE:   56 10:11:31     -115.833759*       0.2668
FIRE:   57 10:11:37     -115.859274*       0.5257
FIRE:   58 10:11:43     -115.882599*       2.0387
FIRE:   59 10:11:46     -115.876671*       5.1170
FIRE:   60 10:11:52     -115.924509*       0.3069
FIRE:   61 10:11:58     -115.924910*       0.2810
FIRE:   62 10:12:03     -115.925697*       0.3178
FIRE:   63 10:12:07     -115.926819*       0.3749
FIRE:   64 10:12:12     -115.928274*       0.4139
FIRE:   65 10:12:18     -115.930117*       0.4184
FIRE:   66 10:12:24     -115.932320*       0.3837
FIRE:   67 10:12:30     -115.934896*       0.3213
FIRE:   68 10:12:34     -115.938114*       0.2967
FIRE:   69 10:12:40     -115.942160*       0.3000
FIRE:   70 10:12:41     -115.947206*       0.2996
FIRE:   71 10:12:46     -115.953388*       0.2953
FIRE:   72 10:12:52     -115.960905*       0.3367
FIRE:   73 10:12:58     -115.969957*       0.2915
FIRE:   74 10:13:04     -115.980665*       0.2934
FIRE:   75 10:13:09     -115.993242*       0.2900
FIRE:   76 10:13:15     -116.008036*       0.3334
FIRE:   77 10:13:21     -116.025820*       0.3022
FIRE:   78 10:13:26     -116.047316*       0.3057
FIRE:   79 10:13:32     -116.074059*       0.3443
FIRE:   80 10:13:38     -116.112831*       0.3923
FIRE:   81 10:13:43     -116.168093*       0.4863
FIRE:   82 10:13:48     -116.239683*       1.2395
FIRE:   83 10:13:54     -116.301073*       3.2546
FIRE:   84 10:13:57     -115.888580*      13.6092
FIRE:   85 10:14:03     -116.282061*       6.5142
FIRE:   86 10:14:08     -116.349926*       4.3611
FIRE:   87 10:14:13     -116.399834*       0.7977
FIRE:   88 10:14:19     -116.371422*       3.1339
FIRE:   89 10:14:25     -116.376816*       2.8342
FIRE:   90 10:14:31     -116.385735*       2.2691
FIRE:   91 10:14:36     -116.395094*       1.5004
FIRE:   92 10:14:42     -116.401743*       0.6276
FIRE:   93 10:14:48     -116.403625*       0.3294
FIRE:   94 10:14:54     -116.403652*       0.3246
FIRE:   95 10:15:00     -116.403706*       0.3152
FIRE:   96 10:15:06     -116.403786*       0.3014
FIRE:   97 10:15:12     -116.403893*       0.2836
FIRE:   98 10:15:18     -116.404013*       0.2622
FIRE:   99 10:15:24     -116.404173*       0.2640
FIRE:  100 10:15:30     -116.404333*       0.2670
FIRE:  101 10:15:35     -116.404520*       0.2704
FIRE:  102 10:15:41     -116.404774*       0.2740
FIRE:  103 10:15:46     -116.405041*       0.2776
FIRE:  104 10:15:52     -116.405401*       0.2809
FIRE:  105 10:15:58     -116.405828*       0.2831
FIRE:  106 10:16:04     -116.406336*       0.2836
FIRE:  107 10:16:10     -116.406977*       0.2815
FIRE:  108 10:16:11     -116.407764*       0.2763
FIRE:  109 10:16:17     -116.408726*       0.2676
FIRE:  110 10:16:23     -116.409874*       0.2560
FIRE:  111 10:16:28     -116.411222*       0.2434
FIRE:  112 10:16:34     -116.412825*       0.2589
FIRE:  113 10:16:39     -116.414707*       0.2620
FIRE:  114 10:16:45     -116.416950*       0.2283
FIRE:  115 10:16:50     -116.419514*       0.2324
FIRE:  116 10:16:56     -116.422438*       0.2309
FIRE:  117 10:16:57     -116.425789*       0.2162
FIRE:  118 10:17:03     -116.429567*       0.2286
FIRE:  119 10:17:06     -116.433826*       0.2415
FIRE:  120 10:17:12     -116.438446*       0.1713
FIRE:  121 10:17:17     -116.443226*       0.1432
FIRE:  122 10:17:23     -116.447872*       0.2382
FIRE:  123 10:17:28     -116.452091*       0.1460
FIRE:  124 10:17:33     -116.455389*       0.2833
FIRE:  125 10:17:37     -116.457191*       0.4338
FIRE:  126 10:17:43     -116.457659*       0.1750
FIRE:  127 10:17:49     -116.457645*       0.2310
FIRE:  128 10:17:55     -116.457672*       0.2014
FIRE:  129 10:18:01     -116.457726*       0.1467
FIRE:  130 10:18:06     -116.457779*       0.0758
Ta-V2O5 relaxation done
CHGNet relaxed structure Full Formula (V4 O10)
Reduced Formula: V2O5
abc   :   6.331677   4.997277   6.442842
angles:  89.999989  90.000043  90.000079
pbc   :       True       True       True
Sites (14)
  #  SP           a         b          c       magmom
---  ----  --------  --------  ---------  -----------
  0  V     0.776167  0.910866  -5e-06     0.0180474
  1  V     0.223788  0.088936  -4e-06     0.0178889
  2  V     0.22381   0.41093    0.499995  0.0178698
  3  V     0.77619   0.588999   0.499995  0.0180418
  4  O     0.500072  0.000525   1.5e-05   0.00293144
  5  O     0.499996  0.500061   0.50001   0.00293007
  6  O     0.891966  0.210648  -1e-06     0.0119969
  7  O     0.108052  0.789147  -1e-06     0.0120525
  8  O     0.108042  0.710731   0.499999  0.0120099
  9  O     0.891955  0.289229   0.499999  0.0120417
 10  O     0.224876  0.249984   0.250002  0.000442982
 11  O     0.775104  0.749984   0.750002  0.000440441
 12  O     0.775105  0.74998    0.249996  0.000440456
 13  O     0.224877  0.24998    0.749996  0.000443026
CHGNet initialized with 400438 Parameters
CHGNet initialized with 400438 Parameters
CHGNet will run on cpu
      Step     Time          Energy         fmax
*Force-consistent energies used in optimization.
FIRE:    0 10:18:12     -116.918056*       8.2636
FIRE:    1 10:18:15     -113.792671*      36.8282
FIRE:    2 10:18:21     -116.908831*      14.3075
FIRE:    3 10:18:23     -117.034975*       7.3715
FIRE:    4 10:18:28     -117.091505*       1.1211
FIRE:    5 10:18:33     -117.091772*       1.0367
FIRE:    6 10:18:39     -117.092239*       0.8753
FIRE:    7 10:18:45     -117.092787*       0.6517
FIRE:    8 10:18:51     -117.093321*       0.3881
FIRE:    9 10:18:56     -117.093748*       0.2655
FIRE:   10 10:19:03     -117.094069*       0.2813
FIRE:   11 10:19:09     -117.094362*       0.2935
FIRE:   12 10:19:15     -117.094776*       0.3812
FIRE:   13 10:19:20     -117.095337*       0.3574
FIRE:   14 10:19:26     -117.096098*       0.2610
FIRE:   15 10:19:31     -117.096939*       0.2241
FIRE:   16 10:19:37     -117.097794*       0.3516
FIRE:   17 10:19:43     -117.098808*       0.5521
FIRE:   18 10:19:49     -117.100224*       0.5439
FIRE:   19 10:19:55     -117.102039*       0.2935
FIRE:   20 10:20:01     -117.103949*       0.2201
FIRE:   21 10:20:07     -117.106125*       0.2358
FIRE:   22 10:20:13     -117.108875*       0.2014
FIRE:   23 10:20:18     -117.111946*       0.4896
FIRE:   24 10:20:20     -117.115938*       0.3181
FIRE:   25 10:20:26     -117.120398*       0.2259
FIRE:   26 10:20:32     -117.125912*       0.1827
FIRE:   27 10:20:37     -117.132080*       0.4828
FIRE:   28 10:20:43     -117.138222*       0.5662
FIRE:   29 10:20:49     -117.143188*       0.9741
FIRE:   30 10:20:54     -117.144016*       1.7581
FIRE:   31 10:21:00     -117.147114*       0.1575
FIRE:   32 10:21:06     -117.145205*       1.4733
FIRE:   33 10:21:12     -117.146086*       1.1555
FIRE:   34 10:21:18     -117.147114*       0.5863
FIRE:   35 10:21:24     -117.147501*       0.1122
FIRE:   36 10:21:29     -117.147514*       0.1053
FIRE:   37 10:21:35     -117.147528*       0.1025
FIRE:   38 10:21:41     -117.147541*       0.1019
FIRE:   39 10:21:47     -117.147568*       0.1013
FIRE:   40 10:21:53     -117.147594*       0.1005
FIRE:   41 10:21:59     -117.147621*       0.0997
alpha-V2O5 relaxation done
CHGNet relaxed structure Full Formula (V4 O10)
Reduced Formula: V2O5
abc   :   3.676327   4.108809  11.817436
angles:  89.999991  90.000001  89.999996
pbc   :       True       True       True
Sites (14)
  #  SP       a         b         c      magmom
---  ----  ----  --------  --------  ----------
  0  V5+   -0    0.901661  0.149606  0.00280577
  1  V5+    0.5  0.098339  0.350394  0.00280493
  2  V5+    0.5  0.098339  0.649606  0.00280564
  3  V5+   -0    0.901661  0.850395  0.00280446
  4  O2-   -0    0.992946  0         0.00467795
  5  O2-   -0    0.506065  0.14633   0.00305995
  6  O2-    0.5  0.992457  0.182077  0.00366482
  7  O2-   -0    0.007543  0.317923  0.00366476
  8  O2-    0.5  0.493935  0.35367   0.00306009
  9  O2-    0.5  0.007054  0.5       0.00467798
 10  O2-    0.5  0.493935  0.64633   0.00305997
 11  O2-    0    0.007543  0.682077  0.0036648
 12  O2-    0.5  0.992457  0.817923  0.00366491
 13  O2-   -0    0.506065  0.85367   0.00305988
```

**Comment by BowenD-UCB** [comment]
Hi, 
I tested your code, and the same code runs on CUDA with no issue on my platform with CUDA available.
On platform where CUDA is not avaible, I get
`RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx`

Can you please test the following codes and see the outputs?
```
import torch
from chgnet.model import CHGNet

# Load pretrained CHGNet
model = CHGNet.load()

# Check if CUDA is available
if torch.cuda.is_available():  
    num_devices = torch.cuda.device_count()
    print(f'Number of CUDA devices: {num_devices}')
    
    for i in range(num_devices):
        device = torch.device(f'cuda:{i}')
        print(f'Device name: {torch.cuda.get_device_name(i)}')

        # Check whether we can move CHGNet to this device
        model.to(f'cuda:{i}')
        print(f"CHGNet is on device {i}")

        # Now your model is on the CUDA device with ID 'i'
else: 
    print('CUDA is not available.')
    
try:
    model.to('cuda')
except:
    raise Exception('can not move to cuda')
```

**Comment by M9JS** [comment]
Here is the output, does it means that I didn't compiled torch with CUDA? Should I download a torch lib consisted with my cuda version?
```
CHGNet initialized with 400438 Parameters
CUDA is not available.
Traceback (most recent call last):
  File "/home/jinshi/CHGNet/cuda_test.py", line 25, in <module>
    model.to('cuda')
  File "/home/jinshi/anaconda3/envs/net/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/jinshi/anaconda3/envs/net/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/jinshi/anaconda3/envs/net/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/jinshi/anaconda3/envs/net/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/jinshi/anaconda3/envs/net/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/jinshi/anaconda3/envs/net/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jinshi/CHGNet/cuda_test.py", line 27, in <module>
    raise Exception('can not move to cuda')
Exception: can not move to cuda
```

**Comment by BowenD-UCB** [comment]
Yes, you need a torch that's compatible with your cuda version. Please refer to the pytorch installation resources like: https://pytorch.org/get-started/locally/

**Comment by M9JS** [comment]
Thanks!
